### ISSUE TITLE
Weaker range of cropping for SSL

### ISSUE THREAD

**Issue by nimaous** [inspire-group/SSD#2]
Hi

Thanks for your nice work. I wonder why you prefer to choose a weaker cropping range for[ SSL ](https://github.com/inspire-group/SSD/blob/main/data.py#L40) in compare to typical Simclr transformations.

**Comment by VSehwag** [comment]
We didn't heavily experiment with the choice of transformations in SimCLR's augmentation pipeline. However, we found a direct correlation between quality of learned representations (commonly measured using linear read-off accuracy) and success in outlier detection. Using aggressive transformations is known to help in self-supervised learning, thus it was a natural choice for us to use them.
