### ISSUE TITLE
Checkpoint content and path?

### ISSUE THREAD

**Issue by laetella** [inspire-group/SSD#3]
When I try to run the eval_ssdk.py, I found that the checkpoint parameter is necessary. 
I create a file named test.txt as ckpt. However, there is an error with whis file :

EOFError: Ran out of input.

What's the format of dataset and checkpoint? Could you please share these two files with us?

**Comment by VSehwag** [comment]
I've added links to pre-trained models (along with command to reproduce results) on the cifar-10 dataset. Check out the end of the updated readme file.
