### ISSUE TITLE
How to reproduce SSD+?

### ISSUE THREAD

**Issue by linhaowei1** [inspire-group/SSD#5]
I only saw SupCE mode for using label information, but I wonder if SSD+ can be reproduced using this code base?

**Comment by lykasbongbongbong** [comment]
Hi! I'm wondering the same question too! I saw that in losses.py, the SupConLoss seems probably able to reproduce SSD+ if labels are provided, but I'm not quite sure. Correct me if I'm wrong! :)

**Comment by VSehwag** [comment]
Indeed, when labels are provided, the SupConLoss is used to train SSD+ models.
