### ISSUE TITLE
training on Imagenet

### ISSUE THREAD

**Issue by rahilgholami** [inspire-group/SSD#6]
Hi, thank you for providing the code!

In the paper you reported some results when model was trained on Imagenet but you didn't mention the details about the data augmentation, neither in the paper nor in your code (data.py).
I was wondering if you resize Imagenet and you use the same augmentation as cifar10 for training?

**Comment by VSehwag** [comment]
Hi, 

Since self-supervised training was extremely resource intensive on ImageNet (particularly due to large batch-size requirement for SimCLR), we used pre-trained models from the SimCLR repo for ImageNet.
