### ISSUE TITLE
What exactly the type of training data you used in your method?

### ISSUE THREAD

**Issue by mike-egg123** [inspire-group/SSD#9]
In your paper, you say that your method outperforms most existing detectors based on unlabeled data by a large margin. And you say that most unsupervised method such as auto-encoder is just like the random prediction. **I doubt that**. Because I have just completed a project of machine learning lesson. It's a task about image-level OOD. The training data is completely clean, which means that it's in-distribution, and the testing data is half IOD and half OOD. I used the CNN as the encoder and decoder, and achieve the 0.93 AUC score. The data I used is as follow:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/59782185/200161246-841f7875-bfe5-4f47-ab1c-21a33020d39e.png">

**Comment by VSehwag** [comment]
Can you share a link to some report regarding this project, which I can take a look at for further details. Regarding our take on previous works, all results for previous works are adopted from previous peer-reviewed publications.
